// ============================================================================
// SquareTapToPayPlugin — Capacitor bridge to Square's Mobile Payments SDK
// ios/App/App/Plugins/SquareTapToPay/SquareTapToPayPlugin.swift
// ============================================================================
// Exposes 5 methods to the web layer:
//   initialize, isAvailable, startPayment, getAuthorizationState,
//   presentSettings
//
// SDK reference:
//   https://developer.squareup.com/docs/mobile-payments-sdk/ios
//
// The SDK is added to the App target via Swift Package Manager — see
// SETUP_NATIVE.md for the exact Xcode steps. Add the package URL
// https://github.com/square/mobile-payments-sdk-ios @ 2.5.0 to the App target
// (not the CapApp-SPM module, whose Package.swift is regenerated by `cap sync`).
//
// When the SDK is NOT linked into the target, every method rejects with a
// clear error so the project still builds on machines without it configured.
// ============================================================================

import Capacitor
import CoreLocation
import Foundation
import Security
import UIKit

#if canImport(SquareMobilePaymentsSDK)
import SquareMobilePaymentsSDK

/// Debug-only console logger. All previous `sqLog(...)` call sites in this
/// file route through here so production (TestFlight/App Store) builds don't
/// leak diagnostics; flip the `#if DEBUG` guard to enable them temporarily.
fileprivate func sqLog(_ message: String) {
    #if DEBUG
    print(message)
    #endif
}

@objc(SquareTapToPayPlugin)
public class SquareTapToPayPlugin: CAPPlugin {

    /// Currently in-flight payment call. The Square SDK reports completion via
    /// the PaymentManagerDelegate, so we hold the call here until a delegate
    /// callback fires and resolves/rejects it.
    private var pendingPaymentCall: CAPPluginCall?
    private var paymentHandle: PaymentHandle?
    private var paymentDelegate: PaymentDelegateBridge?

    /// Tracks whether `MobilePaymentsSDK.initialize(...)` has been called.
    /// Accessing `MobilePaymentsSDK.shared` before this is true is a fatal
    /// error inside the SDK — every public method below must check this flag.
    private var isInitialized = false

    /// Square's Mobile Payments SDK requires CoreLocation authorization before
    /// processing any Tap to Pay transaction. We hold the manager + delegate
    /// here so they outlive the async `requestWhenInUseAuthorization` flow.
    private var locationManager: CLLocationManager?
    private var locationDelegate: LocationDelegateBridge?

    /// Held strongly so the SDK's weakly-referenced observer stays alive for
    /// the lifetime of the plugin. Registered once after authorization.
    private var readerObserver: ReaderObserverBridge?

    /// One-shot callback fired the next time a Tap to Pay reader connects.
    /// Currently used by `activateReader()` (and the legacy `presentSettings`
    /// helper) to wait for the embedded reader to attach after Square's
    /// settings sheet has had a chance to run. Held on the main queue.
    private var readerWaitCompletion: ((Bool) -> Void)?

    /// The currently in-flight `activateReader()` call. Held until the reader
    /// connects, the user dismisses Square's sheet manually, or the safety
    /// timeout fires. Set to nil between activations so a fresh call can take
    /// over after the previous one resolved.
    private var pendingActivationCall: CAPPluginCall?

    /// Tracks the safety-timeout work item for the active activateReader()
    /// call so we can cancel it when the reader connects or the user cancels.
    private var activationTimeoutWorkItem: DispatchWorkItem?

    /// Tracks the 5-second auto-dismiss work item for the active activateReader()
    /// call. We dismiss Square's settings sheet on a short timer so the artist
    /// isn't staring at it on the dashboard; the reader keeps trying to attach
    /// in the background via the still-active ReaderObserver. Cancelled if the
    /// reader connects before 5s elapse.
    private var activationAutoDismissWorkItem: DispatchWorkItem?

    /// True for the brief window between our auto-dismiss work item calling
    /// `dismissSettings()` and the `presentSettings` completion handler firing.
    /// The completion treats user-driven dismissals as `cancelled`; this flag
    /// lets it tell those apart from our programmatic dismiss so we don't
    /// abort an activation that's still legitimately in progress.
    private var activationAutoDismissed = false

    /// Square's ReaderModel rawValue for the embedded Tap to Pay on iPhone
    /// reader. Stored as an Int constant so the wait helper can match without
    /// importing the enum case directly (rawValue is stable across SDK minor
    /// versions; the enum case name has shifted).
    private static let tapToPayReaderModelRawValue = 3

    private static let locationDeniedMessage =
        "Location access is required for Tap to Pay. Please enable it in Settings > Privacy > Location Services."

    // ── initialize ──────────────────────────────────────────────────────────

    @objc func initialize(_ call: CAPPluginCall) {
        sqLog("SquareTapToPay: initialize called")
        guard let applicationId = call.getString("squareApplicationID"),
              let accessToken = call.getString("accessToken"),
              let locationId = call.getString("locationId") else {
            call.reject("squareApplicationID, accessToken, and locationId are required")
            return
        }

        // Square's SDK touches UIKit (UIApplication.connectedScenes,
        // UIWindowScene.interfaceOrientation, etc.) during initialize() and
        // authorize(). Capacitor dispatches plugin methods on a background
        // "bridge" queue, so every Square SDK call must hop to main.
        DispatchQueue.main.async {
            // Bring the SDK up before touching `.shared` for the first time.
            // Safe to call once per process; guard with isInitialized.
            if !self.isInitialized {
                MobilePaymentsSDK.initialize(
                    applicationLaunchOptions: nil,
                    squareApplicationID: applicationId
                )
                self.isInitialized = true
                sqLog("SquareTapToPay: SDK initialized")
            }

            let authState = MobilePaymentsSDK.shared.authorizationManager.state
            sqLog("SquareTapToPay: auth state = \(authState)")

            // Calling authorize() again after a successful auth fails with
            // "authorization_already_authorized". Check state first and skip.
            if authState == .authorized {
                sqLog("SquareTapToPay: already authorized, skipping")
                self.completeInitialize(call: call)
                return
            }

            sqLog("SquareTapToPay: calling authorize with locationId=\(locationId)")
            MobilePaymentsSDK.shared.authorizationManager.authorize(
                withAccessToken: accessToken,
                locationID: locationId
            ) { error in
                if let error = error {
                    let ns = error as NSError
                    sqLog("SquareTapToPay: authorize error domain=\(ns.domain) code=\(ns.code) userInfo=\(ns.userInfo)")

                    // Re-check state on the main thread — the SDK may have
                    // transitioned to .authorized even when reporting an error
                    // ("already_authorized" is the canonical case).
                    DispatchQueue.main.async {
                        let postState = MobilePaymentsSDK.shared.authorizationManager.state
                        let errorString = "\(error)"
                        let userInfoString = "\(ns.userInfo)"
                        let alreadyAuthorized =
                            ns.userInfo["code"] as? String == "authorization_already_authorized" ||
                            errorString.contains("already_authorized") ||
                            userInfoString.contains("already_authorized") ||
                            ns.localizedDescription.lowercased().contains("already_authorized") ||
                            ns.localizedDescription.lowercased().contains("already authorized") ||
                            postState == .authorized

                        if alreadyAuthorized {
                            sqLog("SquareTapToPay: treating already_authorized as success")
                            self.isInitialized = true
                            self.completeInitialize(call: call)
                            return
                        }

                        call.reject(
                            "Square authorization failed: \(ns.localizedDescription)",
                            "\(ns.code)",
                            error,
                            [
                                "message": ns.localizedDescription,
                                "code": ns.code,
                                "domain": ns.domain,
                                "userInfo": Self.stringifyUserInfo(ns.userInfo)
                            ]
                        )
                    }
                    return
                }
                DispatchQueue.main.async {
                    self.completeInitialize(call: call)
                }
            }
        }
    }

    /// Finishes the initialize() flow after Square authorization succeeds.
    /// Resolves the JS promise as soon as authorization + CoreLocation
    /// permission are settled. This path is intentionally silent: it does NOT
    /// open Square's settings sheet (which is what kicks the embedded Tap to
    /// Pay reader into the connected state). Reader activation is now a
    /// separate, just-in-time step driven by `activateReader()` so the artist
    /// only sees the branded activation overlay when they navigate to POS or
    /// Event Mode, not on every dashboard cold-start.
    private func completeInitialize(call: CAPPluginCall) {
        sqLog("SquareTapToPay: completeInitialize - awaiting location permission before resolving")
        ensureLocationPermission { [weak self] granted, _ in
            guard let self = self else { return }
            sqLog("SquareTapToPay: completeInitialize - location permission granted=\(granted)")

            // Register the observer so `readerConnected` notifyListeners can
            // fire later regardless of whether activateReader is in flight.
            self.registerReaderObserverIfNeeded()
            // Apple T&C linking is fire-and-forget; if it fails, the first
            // activateReader() call will surface the underlying error.
            self.linkAppleAccountIfNeeded()

            call.resolve([
                "status": "authorized",
                "locationGranted": granted
            ])
        }
    }

    // ── activateReader ──────────────────────────────────────────────────────

    /// Just-in-time activation entry point — drives the embedded Tap to Pay
    /// reader onto `ReaderManager.readers` by presenting Square's settings
    /// sheet, then dismissing it programmatically via
    /// `SettingsManager.dismissSettings()` as soon as `readerWasAdded` fires
    /// for `ReaderModel.tapToPay`. Surfaced to JS so the branded activation
    /// overlay can call this at POS/Event Mode mount time instead of cold
    /// dashboard load.
    ///
    /// Resolves with one of:
    ///   - `{ status: "alreadyConnected" }` — reader already attached
    ///   - `{ status: "connected" }` — reader attached via this call
    ///   - `{ status: "cancelled" }` — user dismissed Square's sheet
    ///   - `{ status: "timeout" }` — 90s safety timeout fired
    ///
    /// Single-flight: a second `activateReader()` while one is already in
    /// progress rejects with a clear message so JS-side dedup catches the
    /// race instead of double-presenting the sheet.
    @objc func activateReader(_ call: CAPPluginCall) {
        sqLog("SquareTapToPay: activateReader called")
        guard isInitialized else {
            call.reject("Square SDK is not initialized. Call initialize() first.")
            return
        }

        DispatchQueue.main.async { [weak self] in
            guard let self = self else { return }

            if self.pendingActivationCall != nil {
                sqLog("SquareTapToPay: activateReader already in flight, rejecting duplicate")
                call.reject("Reader activation already in progress.")
                return
            }

            if self.isTapToPayReaderConnected() {
                sqLog("SquareTapToPay: activateReader - reader already connected")
                call.resolve(["status": "alreadyConnected"])
                return
            }

            guard let presenter = self.bridge?.viewController else {
                call.reject("No host view controller available to present Square UI.")
                return
            }

            self.pendingActivationCall = call
            call.keepAlive = true
            self.activationAutoDismissed = false
            let activationStart = Date()

            // Single-shot resolver: only the first reason to resolve wins, the
            // rest are no-ops. Always runs on the main queue so plugin state
            // mutations stay serialized.
            let resolveActivation: (String) -> Void = { [weak self] status in
                guard let self = self else { return }
                guard let pending = self.pendingActivationCall else { return }
                sqLog("SquareTapToPay: activateReader resolving with status=\(status)")
                self.pendingActivationCall = nil
                self.readerWaitCompletion = nil
                self.activationTimeoutWorkItem?.cancel()
                self.activationTimeoutWorkItem = nil
                self.activationAutoDismissWorkItem?.cancel()
                self.activationAutoDismissWorkItem = nil
                self.activationAutoDismissed = false
                pending.resolve(["status": status])
            }

            // Reader-arrived path. Square's docs guarantee the
            // `presentSettings` completion fires after `dismissSettings()` so
            // we lean on that to drop the sheet here instead of touching the
            // presented view controller stack ourselves. The "before dismiss"
            // vs "after dismiss" log split is the diagnostic that tells us
            // whether the 5-second auto-dismiss approach is viable: if the
            // reader still connects after we close the sheet, this strategy
            // is the right call. If it never connects post-dismiss, we'd
            // need to revert to dismiss-on-connect.
            self.readerWaitCompletion = { [weak self] _ in
                guard let self = self else { return }
                let elapsedMs = Int(Date().timeIntervalSince(activationStart) * 1000)
                if self.activationAutoDismissed {
                    sqLog("SquareTapToPay: activateReader - reader connected after dismiss! (\(elapsedMs)ms elapsed)")
                } else {
                    sqLog("SquareTapToPay: activateReader - reader connected before dismiss (\(elapsedMs)ms elapsed)")
                    _ = MobilePaymentsSDK.shared.settingsManager.dismissSettings()
                }
                resolveActivation("connected")
            }

            // 5-second auto-dismiss. Drops Square's settings sheet so the
            // artist isn't staring at it; the ReaderObserver stays subscribed
            // so a late-arriving `readerWasAdded` still resolves the call via
            // `readerWaitCompletion` above. We do NOT clear `pendingActivationCall`
            // here — the promise stays in flight until either the reader
            // connects or the 90s safety timeout fires.
            let autoDismissWork = DispatchWorkItem { [weak self] in
                guard let self = self else { return }
                guard self.pendingActivationCall != nil else { return }
                sqLog("SquareTapToPay: activateReader - auto-dismissing settings sheet (reader still connecting in background)")
                self.activationAutoDismissed = true
                _ = MobilePaymentsSDK.shared.settingsManager.dismissSettings()
            }
            self.activationAutoDismissWorkItem = autoDismissWork
            DispatchQueue.main.asyncAfter(deadline: .now() + 5.0, execute: autoDismissWork)

            // 90-second safety timeout. Cancellable so the success path
            // doesn't fire it after we've already resolved.
            let timeoutWork = DispatchWorkItem { [weak self] in
                guard let self = self else { return }
                guard self.pendingActivationCall != nil else { return }
                sqLog("SquareTapToPay: activateReader timeout — dismissing settings")
                self.notifyListeners("readerActivationTimedOut", data: [:])
                _ = MobilePaymentsSDK.shared.settingsManager.dismissSettings()
                resolveActivation("timeout")
            }
            self.activationTimeoutWorkItem = timeoutWork
            DispatchQueue.main.asyncAfter(deadline: .now() + 90.0, execute: timeoutWork)

            sqLog("SquareTapToPay: activateReader - presenting settings (will auto-dismiss in 5s)")
            MobilePaymentsSDK.shared.settingsManager.presentSettings(with: presenter) { error in
                DispatchQueue.main.async {
                    if let error = error {
                        sqLog("SquareTapToPay: activateReader presentSettings error: \(error.localizedDescription)")
                    } else {
                        sqLog("SquareTapToPay: activateReader presentSettings dismissed")
                    }
                    // Our auto-dismiss closed the sheet — keep waiting silently
                    // for the reader to finish attaching in the background.
                    // Don't resolve as cancelled; the reader-arrived path or
                    // the 90s safety timeout will resolve the call.
                    if self.activationAutoDismissed {
                        sqLog("SquareTapToPay: activateReader - settings closed via auto-dismiss, awaiting reader silently")
                        return
                    }
                    // If a resolution already happened (reader connected, or
                    // timeout fired and called dismissSettings) this no-ops.
                    // Otherwise the user closed the sheet manually.
                    if self.pendingActivationCall != nil {
                        resolveActivation("cancelled")
                    }
                }
            }
        }
    }

    // ── dismissActivation ───────────────────────────────────────────────────

    /// Force-dismisses Square's settings sheet if our branded overlay needs
    /// to take it down (e.g., user tapped Cancel on the overlay, or a higher-
    /// priority flow takes over the screen). Safe to call when the sheet
    /// isn't presented — returns `dismissed: false` in that case.
    @objc func dismissActivation(_ call: CAPPluginCall) {
        sqLog("SquareTapToPay: dismissActivation called")
        guard isInitialized else {
            call.resolve(["dismissed": false])
            return
        }
        DispatchQueue.main.async {
            let dismissed = MobilePaymentsSDK.shared.settingsManager.dismissSettings()
            sqLog("SquareTapToPay: dismissActivation - dismissed=\(dismissed)")
            call.resolve(["dismissed": dismissed])
        }
    }

    // ── hasProximityReaderEntitlement ───────────────────────────────────────

    /// Reads the running binary's own entitlements via the Security framework
    /// to confirm Apple's `com.apple.developer.proximity-reader.payment.acceptance`
    /// capability is present. JS uses this to hide every Tap to Pay surface in
    /// builds where Apple hasn't granted the entitlement yet, defense-in-depth
    /// on top of `tap_to_pay_enabled` in the tenant record. Always resolves —
    /// false on simulator / debug builds where SecTask returns nothing useful.
    @objc func hasProximityReaderEntitlement(_ call: CAPPluginCall) {
        let entitled = Self.readProximityReaderEntitlement()
        sqLog("SquareTapToPay: hasProximityReaderEntitlement = \(entitled)")
        call.resolve(["entitled": entitled])
    }

    private static func readProximityReaderEntitlement() -> Bool {
        #if DEBUG
        // Xcode debug-signed builds don't reliably bundle embedded.mobileprovision,
        // and dev devices are already provisioned with a profile that includes
        // the entitlement. Trust the build configuration here so the activation
        // gate mounts the branded overlay during on-device testing.
        sqLog("SquareTapToPay: DEBUG build — assuming entitlement is present")
        return true
        #else
        let key = "com.apple.developer.proximity-reader.payment.acceptance"

        // Read the embedded provisioning profile from the app bundle.
        // TestFlight, ad-hoc, and App Store builds all contain this file
        // when the app is signed with a profile that declares entitlements.
        guard let profileURL = Bundle.main.url(forResource: "embedded", withExtension: "mobileprovision"),
              let profileData = try? Data(contentsOf: profileURL),
              let profileString = String(data: profileData, encoding: .ascii) else {
            sqLog("SquareTapToPay: no embedded.mobileprovision found — assuming no entitlement")
            return false
        }

        // The profile is a CMS-wrapped binary blob with an embedded XML plist.
        // We don't need to parse the plist — just check whether the entitlement
        // key appears in the profile text. False positives are not possible
        // because the key is unique and only appears in profiles that include it.
        let entitled = profileString.contains(key)
        sqLog("SquareTapToPay: embedded profile entitlement check = \(entitled)")
        return entitled
        #endif
    }

    /// NSError userInfo values aren't all JSON-serializable; coerce to strings
    /// so Capacitor can pass them through to the JS layer intact.
    private static func stringifyUserInfo(_ info: [String: Any]) -> [String: String] {
        var out: [String: String] = [:]
        for (k, v) in info {
            out[k] = String(describing: v)
        }
        return out
    }

    // ── isAvailable ─────────────────────────────────────────────────────────

    @objc func isAvailable(_ call: CAPPluginCall) {
        sqLog("SquareTapToPay: isAvailable called, initialized=\(isInitialized)")
        // Web layer calls this on page load — before initialize() has run —
        // so we must answer without touching `.shared`.
        guard isInitialized else {
            call.resolve([
                "available": false,
                "isDeviceCapable": false,
                "reason": "SDK not initialized"
            ])
            return
        }

        // Square SDK access must happen on the main thread; the device
        // capability check reads UIKit state internally.
        DispatchQueue.main.async {
            // SDK 2.5.0 moved the device-capability check onto TapToPaySettings,
            // reachable through ReaderManager. isDeviceCapable returns true for
            // iPhone XS+ on iOS 16.7+.
            let supportsTapToPay = MobilePaymentsSDK.shared.readerManager
                .tapToPaySettings
                .isDeviceCapable
            call.resolve([
                "available": supportsTapToPay,
                "isDeviceCapable": supportsTapToPay
            ])
        }
    }

    // ── getAuthorizationState ───────────────────────────────────────────────

    @objc func getAuthorizationState(_ call: CAPPluginCall) {
        guard isInitialized else {
            call.resolve(["authorized": false])
            return
        }
        // Authorization state reads from shared SDK state that's mutated on
        // the main thread; query it there to avoid UI API thread violations.
        DispatchQueue.main.async {
            let state = MobilePaymentsSDK.shared.authorizationManager.state
            call.resolve(["authorized": state == .authorized])
        }
    }

    // ── startPayment ────────────────────────────────────────────────────────

    @objc func startPayment(_ call: CAPPluginCall) {
        guard isInitialized else {
            call.reject("Square SDK is not initialized. Call initialize() first.")
            return
        }
        guard let amountCents = call.getInt("amountCents") else {
            call.reject("amountCents is required")
            return
        }
        let currencyCode = call.getString("currencyCode") ?? "USD"
        let note = call.getString("note")
        sqLog("SquareTapToPay: startPayment called, amount=\(amountCents)")

        // Square's SDK presents from a UIViewController and reads UIKit state
        // internally — both the auth state check and startPayment must run on
        // the main thread. Capacitor's bridge.viewController hosts the WKWebView.
        DispatchQueue.main.async { [weak self] in
            guard let self = self,
                  let presenter = self.bridge?.viewController else {
                call.reject("No host view controller available to present Square UI.")
                return
            }

            // Tap to Pay requires authorization first.
            let state = MobilePaymentsSDK.shared.authorizationManager.state
            sqLog("SquareTapToPay: startPayment auth state = \(state)")
            guard state == .authorized else {
                call.reject("Square SDK is not authorized. Call initialize() first.")
                return
            }

            // Square's SDK requires CoreLocation authorization before each
            // Tap to Pay transaction; otherwise startPayment rejects with
            // "Location permission has not been granted to your application."
            // We block on ensureLocationPermission until the system prompt
            // fully resolves and the delegate fires — only then is
            // CLLocationManager.authorizationStatus stable enough for the
            // SDK's internal synchronous check inside startPayment.
            sqLog("SquareTapToPay: startPayment - checking location permission before SDK call")
            self.ensureLocationPermission { [weak self] granted, errorMessage in
                guard let self = self else { return }
                sqLog("SquareTapToPay: startPayment - location permission resolved, granted=\(granted)")
                if !granted {
                    call.reject(errorMessage ?? Self.locationDeniedMessage)
                    return
                }
                DispatchQueue.main.async {
                    sqLog("SquareTapToPay: payment additionalMethods = tapToPay")
                    sqLog("SquareTapToPay: tapToPaySettings.isDeviceCapable = \(MobilePaymentsSDK.shared.readerManager.tapToPaySettings.isDeviceCapable)")
                    // initialize() now activates the reader via the settings
                    // sheet, so we no longer block startPayment waiting for
                    // pairing. Log the current state and proceed — Square's
                    // own UI will surface a "connect hardware" prompt if the
                    // reader is genuinely missing.
                    if !self.isTapToPayReaderConnected() {
                        sqLog("SquareTapToPay: warning - no Tap to Pay reader connected at startPayment; proceeding anyway")
                    } else {
                        sqLog("SquareTapToPay: Tap to Pay reader connected, proceeding to startPayment")
                    }
                    self.beginPayment(
                        call: call,
                        amountCents: amountCents,
                        currencyCode: currencyCode,
                        note: note,
                        presenter: presenter
                    )
                }
            }
        }
    }

    /// Runs after the SDK + location checks pass. Always invoked on the main
    /// queue (the location helper dispatches its completion to main).
    private func beginPayment(
        call: CAPPluginCall,
        amountCents: Int,
        currencyCode: String,
        note: String?,
        presenter: UIViewController
    ) {
        // Map ISO 4217 → Square's currency enum. Default to USD; surface a
        // clear error if the caller passes something unsupported.
        let currency: Currency
        switch currencyCode.uppercased() {
        case "USD": currency = .USD
        case "CAD": currency = .CAD
        case "GBP": currency = .GBP
        case "AUD": currency = .AUD
        case "JPY": currency = .JPY
        case "EUR": currency = .EUR
        default:
            call.reject("Unsupported currency: \(currencyCode)")
            return
        }

        let amountMoney = Money(amount: UInt(amountCents), currency: currency)
        let params = PaymentParameters(
            paymentAttemptID: UUID().uuidString,
            amountMoney: amountMoney,
            processingMode: .onlineOnly
        )
        if let note = note { params.note = note }

        let promptParams = PromptParameters(
            mode: .default,
            additionalMethods: .all
        )

        self.pendingPaymentCall = call
        // Capacitor releases the call after the bridge method returns
        // unless we keep it alive. The Square delegate resolves it later.
        call.keepAlive = true

        let delegate = PaymentDelegateBridge(owner: self)
        self.paymentDelegate = delegate

        self.paymentHandle = MobilePaymentsSDK.shared.paymentManager.startPayment(
            params,
            promptParameters: promptParams,
            from: presenter,
            delegate: delegate
        )
        sqLog("SquareTapToPay: payment started with default mode, all methods")
    }

    // ── Location permission ─────────────────────────────────────────────────

    /// Resolves with `(granted, errorMessage)` after the current
    /// CLLocationManager authorization status is known. If the status is
    /// `.notDetermined`, this triggers the system prompt and waits for the
    /// delegate callback before completing. Must be called on the main queue.
    private func ensureLocationPermission(completion: @escaping (Bool, String?) -> Void) {
        if locationManager == nil {
            locationManager = CLLocationManager()
        }
        guard let manager = locationManager else {
            sqLog("SquareTapToPay: ensureLocationPermission - failed to create CLLocationManager")
            completion(false, "Unable to create CLLocationManager.")
            return
        }

        let status = manager.authorizationStatus
        sqLog("SquareTapToPay: ensureLocationPermission - status = \(status.rawValue) (\(describeAuthStatus(status)))")
        switch status {
        case .authorizedAlways, .authorizedWhenInUse:
            sqLog("SquareTapToPay: ensureLocationPermission - already granted, completing immediately")
            completion(true, nil)
        case .denied, .restricted:
            sqLog("SquareTapToPay: ensureLocationPermission - denied/restricted, completing with error")
            completion(false, Self.locationDeniedMessage)
        case .notDetermined:
            sqLog("SquareTapToPay: ensureLocationPermission - notDetermined, wiring delegate and requesting permission")
            let bridge = LocationDelegateBridge { [weak self] newStatus in
                guard let self = self else { return }
                sqLog("SquareTapToPay: ensureLocationPermission - delegate fired, newStatus = \(newStatus.rawValue) (\(self.describeAuthStatus(newStatus)))")
                self.locationDelegate = nil
                switch newStatus {
                case .authorizedAlways, .authorizedWhenInUse:
                    completion(true, nil)
                case .denied, .restricted:
                    completion(false, Self.locationDeniedMessage)
                default:
                    completion(false, Self.locationDeniedMessage)
                }
            }
            self.locationDelegate = bridge
            manager.delegate = bridge
            manager.requestWhenInUseAuthorization()
            sqLog("SquareTapToPay: ensureLocationPermission - requestWhenInUseAuthorization called, awaiting delegate")
        @unknown default:
            sqLog("SquareTapToPay: ensureLocationPermission - unknown status, failing")
            completion(false, Self.locationDeniedMessage)
        }
    }

    private func describeAuthStatus(_ status: CLAuthorizationStatus) -> String {
        switch status {
        case .notDetermined: return "notDetermined"
        case .restricted: return "restricted"
        case .denied: return "denied"
        case .authorizedAlways: return "authorizedAlways"
        case .authorizedWhenInUse: return "authorizedWhenInUse"
        @unknown default: return "unknown"
        }
    }

    // ── presentSettings ─────────────────────────────────────────────────────

    /// Presents Square's built-in Mobile Payments SDK settings screen, which
    /// drives the one-time Tap to Pay on iPhone setup (Apple Account link,
    /// device pairing, etc.). After the sheet is dismissed we re-read the
    /// reader list so the logs show whether Tap to Pay registered itself.
    @objc func presentSettings(_ call: CAPPluginCall) {
        sqLog("SquareTapToPay: presentSettings called")
        guard isInitialized else {
            call.reject("SDK not initialized")
            return
        }
        DispatchQueue.main.async { [weak self] in
            guard let self = self,
                  let presenter = self.bridge?.viewController else {
                call.reject("No view controller")
                return
            }
            MobilePaymentsSDK.shared.settingsManager.presentSettings(with: presenter) { error in
                if let error = error {
                    sqLog("SquareTapToPay: presentSettings error: \(error.localizedDescription)")
                    call.reject(error.localizedDescription)
                    return
                }
                sqLog("SquareTapToPay: presentSettings dismissed")
                let readers = MobilePaymentsSDK.shared.readerManager.readers
                sqLog("SquareTapToPay: readers after settings: count=\(readers.count)")
                for reader in readers {
                    sqLog("SquareTapToPay: reader model=\(reader.model)")
                }
                call.resolve()
            }
        }
    }

    // ── Reader observer ────────────────────────────────────────────────────

    /// Attaches our ReaderObserverBridge to the SDK so we get callbacks when
    /// the embedded Tap to Pay reader pairs / unpairs / changes state. The
    /// observer is held strongly on `self` (the SDK keeps a weak ref). Safe
    /// to call multiple times — we only register once.
    private func registerReaderObserverIfNeeded() {
        if readerObserver != nil { return }
        let bridge = ReaderObserverBridge(owner: self)
        self.readerObserver = bridge
        MobilePaymentsSDK.shared.readerManager.add(bridge)
        sqLog("SquareTapToPay: ReaderObserver registered")
    }

    // ── Tap to Pay reader wait helper ──────────────────────────────────────

    /// Returns true if a Tap to Pay on iPhone reader (model rawValue 3) is
    /// currently present in the SDK's reader list.
    private func isTapToPayReaderConnected() -> Bool {
        let readers = MobilePaymentsSDK.shared.readerManager.readers
        return readers.contains { $0.model.rawValue == Self.tapToPayReaderModelRawValue }
    }

    /// Called by ReaderObserverBridge when readerWasAdded fires. Fulfills any
    /// pending activateReader() wait AND emits a `readerConnected` event so
    /// the JS-side overlay can react regardless of whether activateReader was
    /// the trigger (e.g., legacy `presentSettings` flow, manual reset). Only
    /// reacts to model 3 (Tap to Pay on iPhone) — Bluetooth/USB readers go
    /// through their own paths.
    fileprivate func handleReaderAdded(_ readerInfo: ReaderInfo) {
        guard readerInfo.model.rawValue == Self.tapToPayReaderModelRawValue else { return }
        sqLog("SquareTapToPay: handleReaderAdded - tapToPay model attached, firing listeners")
        self.notifyListeners("readerConnected", data: ["model": "tapToPay"])
        if let waiter = self.readerWaitCompletion {
            waiter(true)
        }
    }

    /// Square requires the merchant to link an Apple Account (accept Apple's
    /// Tap to Pay T&Cs) before Tap to Pay payments will run. Fire-and-forget:
    /// initialize() has already resolved, and if linking fails the first
    /// startPayment() will surface the underlying SDK error.
    private func linkAppleAccountIfNeeded() {
        DispatchQueue.main.async {
            let settings = MobilePaymentsSDK.shared.readerManager.tapToPaySettings
            settings.isAppleAccountLinked { linked, error in
                sqLog("SquareTapToPay: Apple account linked = \(linked)")
                if let error = error {
                    let ns = error as NSError
                    sqLog("SquareTapToPay: isAppleAccountLinked error domain=\(ns.domain) code=\(ns.code) message=\(ns.localizedDescription)")
                }
                if linked { return }
                DispatchQueue.main.async {
                    sqLog("SquareTapToPay: linking Apple account...")
                    settings.linkAppleAccount { linkError in
                        if let linkError = linkError {
                            let ns = linkError as NSError
                            sqLog("SquareTapToPay: linkAppleAccount error domain=\(ns.domain) code=\(ns.code) message=\(ns.localizedDescription)")
                        } else {
                            sqLog("SquareTapToPay: Apple account linked successfully")
                        }
                    }
                }
            }
        }
    }

    // ── Delegate callbacks (bridged in from PaymentDelegateBridge) ─────────

    fileprivate func handleDidFinish(_ payment: Payment) {
        guard let call = pendingPaymentCall else { return }
        defer { resetPaymentState() }

        // Pull card brand + last4 when available (online card payments).
        // In SDK 2.5.0, card info hangs off OnlinePayment.cardDetails.card
        // (CardPaymentDetails → Card), not the old sourceType.card path.
        var cardBrand: String?
        var last4: String?
        if let card = (payment as? OnlinePayment)?.cardDetails?.card {
            cardBrand = describeBrand(card.cardBrand)
            last4 = card.last4
        }

        // localID lives on OfflinePayment only in 2.5.0; Tap to Pay is
        // online-only, so there's no client-side ID to surface here.
        call.resolve([
            "status": "success",
            "transactionId": payment.id ?? "",
            "clientTransactionId": "",
            "cardBrand": cardBrand ?? "",
            "last4": last4 ?? ""
        ])
    }

    fileprivate func handleDidFail(_ payment: Payment?, error: Error) {
        guard let call = pendingPaymentCall else { return }
        defer { resetPaymentState() }
        let ns = error as NSError
        sqLog("SquareTapToPay: payment error - \(ns.localizedDescription), code: \(ns.code), userInfo: \(ns.userInfo)")
        call.resolve([
            "status": "error",
            "errorMessage": ns.localizedDescription,
            "errorCode": ns.code,
            "errorDomain": ns.domain,
            "errorUserInfo": Self.stringifyUserInfo(ns.userInfo)
        ])
    }

    fileprivate func handleDidCancel(_ payment: Payment) {
        guard let call = pendingPaymentCall else { return }
        defer { resetPaymentState() }
        call.resolve(["status": "cancelled"])
    }

    private func resetPaymentState() {
        pendingPaymentCall = nil
        paymentHandle = nil
        paymentDelegate = nil
    }

    // SDK 2.5.0 promoted Card.Brand to a top-level CardBrand enum and renamed
    // the JCB case to .jcb (was .JCB). New cases like .squareCapitalCard and
    // .otherBrand are handled by @unknown default.
    private func describeBrand(_ brand: CardBrand) -> String {
        switch brand {
        case .visa: return "VISA"
        case .mastercard: return "MASTERCARD"
        case .americanExpress: return "AMERICAN_EXPRESS"
        case .discover: return "DISCOVER"
        case .discoverDiners: return "DISCOVER_DINERS"
        case .jcb: return "JCB"
        case .chinaUnionPay: return "CHINA_UNION_PAY"
        case .squareGiftCard: return "SQUARE_GIFT_CARD"
        case .interac: return "INTERAC"
        case .eftpos: return "EFTPOS"
        case .felica: return "FELICA"
        case .ebt: return "EBT"
        @unknown default: return "OTHER"
        }
    }
}

// ── PaymentManagerDelegate bridge ─────────────────────────────────────────
// Square's delegate methods are NSObjectProtocol-based and we don't want the
// plugin class itself to conform (keeps the public surface clean). This thin
// bridge forwards every callback to the plugin.

fileprivate final class PaymentDelegateBridge: NSObject, PaymentManagerDelegate {
    weak var owner: SquareTapToPayPlugin?

    init(owner: SquareTapToPayPlugin) {
        self.owner = owner
        super.init()
    }

    func paymentManager(_ paymentManager: PaymentManager, didFinish payment: Payment) {
        owner?.handleDidFinish(payment)
    }

    func paymentManager(_ paymentManager: PaymentManager, didFail payment: Payment, withError error: Error) {
        owner?.handleDidFail(payment, error: error)
    }

    func paymentManager(_ paymentManager: PaymentManager, didCancel payment: Payment) {
        owner?.handleDidCancel(payment)
    }
}

// ── ReaderObserver bridge ─────────────────────────────────────────────────
// Square's ReaderManager pushes reader lifecycle events to a weakly-held
// observer. We forward each callback to the console so we can see — during
// Tap to Pay setup — whether the embedded reader auto-pairs, gets removed,
// or changes status (firmware update, card insertion, etc.).

fileprivate final class ReaderObserverBridge: NSObject, ReaderObserver {
    weak var owner: SquareTapToPayPlugin?

    init(owner: SquareTapToPayPlugin) {
        self.owner = owner
        super.init()
    }

    func readerWasAdded(_ readerInfo: ReaderInfo) {
        sqLog("SquareTapToPay: readerWasAdded — model=\(readerInfo.model) (rawValue=\(readerInfo.model.rawValue)) name=\(readerInfo.name) connection=\(readerInfo.connectionType)")
        owner?.handleReaderAdded(readerInfo)
    }

    func readerWasRemoved(_ readerInfo: ReaderInfo) {
        sqLog("SquareTapToPay: readerWasRemoved — model=\(readerInfo.model) name=\(readerInfo.name)")
    }

    func readerDidChange(_ readerInfo: ReaderInfo, change: ReaderChange) {
        sqLog("SquareTapToPay: readerDidChange — model=\(readerInfo.model) change=\(change)")
    }
}

// ── CLLocationManagerDelegate bridge ──────────────────────────────────────
// CLLocationManagerDelegate is iOS-14+. We fire `onResolved` once the
// authorization status leaves `.notDetermined`. The initial delegate-set
// callback (which can carry `.notDetermined`) is ignored.

fileprivate final class LocationDelegateBridge: NSObject, CLLocationManagerDelegate {
    private let onResolved: (CLAuthorizationStatus) -> Void
    private var fired = false

    init(onResolved: @escaping (CLAuthorizationStatus) -> Void) {
        self.onResolved = onResolved
        super.init()
    }

    func locationManagerDidChangeAuthorization(_ manager: CLLocationManager) {
        let status = manager.authorizationStatus
        guard status != .notDetermined, !fired else { return }
        fired = true
        onResolved(status)
    }
}

#else

// Stub implementation used when SquareMobilePaymentsSDK is not linked into
// the target. Lets the project compile on machines where the SDK hasn't been
// added yet; every method rejects with a clear error.

@objc(SquareTapToPayPlugin)
public class SquareTapToPayPlugin: CAPPlugin {

    private static let notInstalledMessage =
        "Square Mobile Payments SDK not installed"

    @objc func initialize(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func isAvailable(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func getAuthorizationState(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func startPayment(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func presentSettings(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func activateReader(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func dismissActivation(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func hasProximityReaderEntitlement(_ call: CAPPluginCall) {
        call.resolve(["entitled": false])
    }
}

#endif
