// ============================================================================
// SquareTapToPayPlugin — Capacitor bridge to Square's Mobile Payments SDK
// ios/App/App/Plugins/SquareTapToPay/SquareTapToPayPlugin.swift
// ============================================================================
// Exposes 4 methods to the web layer:
//   initialize, isAvailable, startPayment, getAuthorizationState
//
// SDK reference:
//   https://developer.squareup.com/docs/mobile-payments-sdk/ios
//
// The SDK is added to the App target via Swift Package Manager — see
// SETUP_NATIVE.md for the exact Xcode steps. Add the package URL
// https://github.com/square/mobile-payments-sdk-ios @ 2.5.0 to the App target
// (not the CapApp-SPM module, whose Package.swift is regenerated by `cap sync`).
//
// When the SDK is NOT linked into the target, every method rejects with a
// clear error so the project still builds on machines without it configured.
// ============================================================================

import Capacitor
import Foundation
import UIKit

#if canImport(SquareMobilePaymentsSDK)
import SquareMobilePaymentsSDK

@objc(SquareTapToPayPlugin)
public class SquareTapToPayPlugin: CAPPlugin {

    /// Currently in-flight payment call. The Square SDK reports completion via
    /// the PaymentManagerDelegate, so we hold the call here until a delegate
    /// callback fires and resolves/rejects it.
    private var pendingPaymentCall: CAPPluginCall?
    private var paymentHandle: PaymentHandle?
    private var paymentDelegate: PaymentDelegateBridge?

    /// Tracks whether `MobilePaymentsSDK.initialize(...)` has been called.
    /// Accessing `MobilePaymentsSDK.shared` before this is true is a fatal
    /// error inside the SDK — every public method below must check this flag.
    private var isInitialized = false

    // ── initialize ──────────────────────────────────────────────────────────

    @objc func initialize(_ call: CAPPluginCall) {
        guard let applicationId = call.getString("squareApplicationID"),
              let accessToken = call.getString("accessToken"),
              let locationId = call.getString("locationId") else {
            call.reject("squareApplicationID, accessToken, and locationId are required")
            return
        }

        // Bring the SDK up before touching `.shared` for the first time.
        // Safe to call once per process; guard with isInitialized.
        if !isInitialized {
            MobilePaymentsSDK.initialize(
                applicationLaunchOptions: nil,
                squareApplicationID: applicationId
            )
            isInitialized = true
        }

        // The SDK is idempotent — calling authorize() again with the same
        // credentials simply succeeds. So we don't try to detect "already
        // authorized" up here; we just call it.
        MobilePaymentsSDK.shared.authorizationManager.authorize(
            withAccessToken: accessToken,
            locationID: locationId
        ) { error in
            if let error = error {
                call.reject("Square authorization failed: \(error.localizedDescription)")
                return
            }
            call.resolve()
        }
    }

    // ── isAvailable ─────────────────────────────────────────────────────────

    @objc func isAvailable(_ call: CAPPluginCall) {
        // Web layer calls this on page load — before initialize() has run —
        // so we must answer without touching `.shared`.
        guard isInitialized else {
            call.resolve(["available": false, "reason": "SDK not initialized"])
            return
        }

        // SDK 2.5.0 moved the device-capability check onto TapToPaySettings,
        // reachable through ReaderManager. isDeviceCapable returns true for
        // iPhone XS+ on iOS 16.7+.
        let supportsTapToPay = MobilePaymentsSDK.shared.readerManager
            .tapToPaySettings
            .isDeviceCapable
        call.resolve(["available": supportsTapToPay])
    }

    // ── getAuthorizationState ───────────────────────────────────────────────

    @objc func getAuthorizationState(_ call: CAPPluginCall) {
        guard isInitialized else {
            call.resolve(["authorized": false])
            return
        }
        let state = MobilePaymentsSDK.shared.authorizationManager.state
        call.resolve(["authorized": state == .authorized])
    }

    // ── startPayment ────────────────────────────────────────────────────────

    @objc func startPayment(_ call: CAPPluginCall) {
        guard isInitialized else {
            call.reject("Square SDK is not initialized. Call initialize() first.")
            return
        }
        guard let amountCents = call.getInt("amountCents") else {
            call.reject("amountCents is required")
            return
        }
        let currencyCode = call.getString("currencyCode") ?? "USD"
        let note = call.getString("note")

        // Tap to Pay requires authorization first.
        let state = MobilePaymentsSDK.shared.authorizationManager.state
        guard state == .authorized else {
            call.reject("Square SDK is not authorized. Call initialize() first.")
            return
        }

        // Square's SDK presents from a UIViewController. Capacitor's
        // bridge.viewController is the host view controller hosting the
        // WKWebView, so we present from there on the main thread.
        DispatchQueue.main.async { [weak self] in
            guard let self = self,
                  let presenter = self.bridge?.viewController else {
                call.reject("No host view controller available to present Square UI.")
                return
            }

            // Map ISO 4217 → Square's currency enum. Default to USD; surface a
            // clear error if the caller passes something unsupported.
            let currency: Currency
            switch currencyCode.uppercased() {
            case "USD": currency = .USD
            case "CAD": currency = .CAD
            case "GBP": currency = .GBP
            case "AUD": currency = .AUD
            case "JPY": currency = .JPY
            case "EUR": currency = .EUR
            default:
                call.reject("Unsupported currency: \(currencyCode)")
                return
            }

            let amountMoney = Money(amount: UInt(amountCents), currency: currency)
            let params = PaymentParameters(
                paymentAttemptID: UUID().uuidString,
                amountMoney: amountMoney,
                processingMode: .onlineOnly
            )
            if let note = note { params.note = note }

            let promptParams = PromptParameters(
                mode: .default,
                additionalMethods: .all
            )

            self.pendingPaymentCall = call
            // Capacitor releases the call after the bridge method returns
            // unless we keep it alive. The Square delegate resolves it later.
            call.keepAlive = true

            let delegate = PaymentDelegateBridge(owner: self)
            self.paymentDelegate = delegate

            self.paymentHandle = MobilePaymentsSDK.shared.paymentManager.startPayment(
                params,
                promptParameters: promptParams,
                from: presenter,
                delegate: delegate
            )
        }
    }

    // ── Delegate callbacks (bridged in from PaymentDelegateBridge) ─────────

    fileprivate func handleDidFinish(_ payment: Payment) {
        guard let call = pendingPaymentCall else { return }
        defer { resetPaymentState() }

        // Pull card brand + last4 when available (online card payments).
        // In SDK 2.5.0, card info hangs off OnlinePayment.cardDetails.card
        // (CardPaymentDetails → Card), not the old sourceType.card path.
        var cardBrand: String?
        var last4: String?
        if let card = (payment as? OnlinePayment)?.cardDetails?.card {
            cardBrand = describeBrand(card.cardBrand)
            last4 = card.last4
        }

        // localID lives on OfflinePayment only in 2.5.0; Tap to Pay is
        // online-only, so there's no client-side ID to surface here.
        call.resolve([
            "status": "success",
            "transactionId": payment.id ?? "",
            "clientTransactionId": "",
            "cardBrand": cardBrand ?? "",
            "last4": last4 ?? ""
        ])
    }

    fileprivate func handleDidFail(_ payment: Payment?, error: Error) {
        guard let call = pendingPaymentCall else { return }
        defer { resetPaymentState() }
        call.resolve([
            "status": "error",
            "errorMessage": error.localizedDescription
        ])
    }

    fileprivate func handleDidCancel(_ payment: Payment) {
        guard let call = pendingPaymentCall else { return }
        defer { resetPaymentState() }
        call.resolve(["status": "cancelled"])
    }

    private func resetPaymentState() {
        pendingPaymentCall = nil
        paymentHandle = nil
        paymentDelegate = nil
    }

    // SDK 2.5.0 promoted Card.Brand to a top-level CardBrand enum and renamed
    // the JCB case to .jcb (was .JCB). New cases like .squareCapitalCard and
    // .otherBrand are handled by @unknown default.
    private func describeBrand(_ brand: CardBrand) -> String {
        switch brand {
        case .visa: return "VISA"
        case .mastercard: return "MASTERCARD"
        case .americanExpress: return "AMERICAN_EXPRESS"
        case .discover: return "DISCOVER"
        case .discoverDiners: return "DISCOVER_DINERS"
        case .jcb: return "JCB"
        case .chinaUnionPay: return "CHINA_UNION_PAY"
        case .squareGiftCard: return "SQUARE_GIFT_CARD"
        case .interac: return "INTERAC"
        case .eftpos: return "EFTPOS"
        case .felica: return "FELICA"
        case .ebt: return "EBT"
        @unknown default: return "OTHER"
        }
    }
}

// ── PaymentManagerDelegate bridge ─────────────────────────────────────────
// Square's delegate methods are NSObjectProtocol-based and we don't want the
// plugin class itself to conform (keeps the public surface clean). This thin
// bridge forwards every callback to the plugin.

fileprivate final class PaymentDelegateBridge: NSObject, PaymentManagerDelegate {
    weak var owner: SquareTapToPayPlugin?

    init(owner: SquareTapToPayPlugin) {
        self.owner = owner
        super.init()
    }

    func paymentManager(_ paymentManager: PaymentManager, didFinish payment: Payment) {
        owner?.handleDidFinish(payment)
    }

    func paymentManager(_ paymentManager: PaymentManager, didFail payment: Payment, withError error: Error) {
        owner?.handleDidFail(payment, error: error)
    }

    func paymentManager(_ paymentManager: PaymentManager, didCancel payment: Payment) {
        owner?.handleDidCancel(payment)
    }
}

#else

// Stub implementation used when SquareMobilePaymentsSDK is not linked into
// the target. Lets the project compile on machines where the SDK hasn't been
// added yet; every method rejects with a clear error.

@objc(SquareTapToPayPlugin)
public class SquareTapToPayPlugin: CAPPlugin {

    private static let notInstalledMessage =
        "Square Mobile Payments SDK not installed"

    @objc func initialize(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func isAvailable(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func getAuthorizationState(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }

    @objc func startPayment(_ call: CAPPluginCall) {
        call.reject(Self.notInstalledMessage)
    }
}

#endif
