platform :ios, '16.0'

target 'App' do
  use_frameworks!

  # Square Mobile Payments SDK (CocoaPods handles binary framework embedding)
  pod 'SquareMobilePaymentsSDK'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
    end
  end
end
