// ============================================================================
// BridgeViewController — Capacitor bridge with app-local plugins registered
// ios/App/App/BridgeViewController.swift
// ============================================================================
// Capacitor's auto-registration reads `packageClassList` from the synced
// capacitor.config.json. That list is regenerated by `cap sync` from the
// npm-installed `@capacitor/*` plugins, so app-local plugins defined inside
// this Xcode target (e.g. SquareTapToPayPlugin) never appear there.
//
// We register those plugins manually in `capacitorDidLoad()`, which the
// CAPBridgeViewController calls right after the bridge is constructed.
// `Main.storyboard` points the initial view controller at this subclass.
// ============================================================================

import Capacitor
import UIKit

class BridgeViewController: CAPBridgeViewController {
    override open func capacitorDidLoad() {
        bridge?.registerPluginInstance(SquareTapToPayPlugin())
    }
}
